server:
  port: 8081
spring:
  application:
    name: products
  mvc:
    servlet:
      path: /api

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:h2:file:./data/productDB
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration/h2
    baseline-on-migrate: true   #  Allows baselining an existing database to avoid applying all historical migrations to an existing schema.

springdoc:
  api-docs:
    path: /v3/api-docs  # /ecom/products/api/ may need to add this to expose /v3/api-docs/swagger-config though gateway, need to consider once keycloak can restirct this
    # else no need to expose swagger url by apigateway;
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yml
    #   mvc.servlet.path: /api  after giving this, swagger-ui is exposed like /api/swagger-ui.html
logging:
  level:
    org:
      flywaydb: DEBUG
    com:
      example:
        products:
        repository: DEBUG
        service: DEBUG
        controller: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: /management  # mvc.servlet.path: /api  is over riding this

  # need to update the path, it is better to move /api/v1 in class.

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s